<?php

return [
    'version' => '1.7.9',
    'env'=>[
        [
            'name'=>"Setup",
            'slug'=>"setup",
            'icon'=>"ni ni-settings",
            'fields'=>[
                ['key'=>'APP_NAME','value'=>'Site name'],   
                ['key'=>'APP_URL','value'=>'http://localhost'],
                ['key'=>'IGNORE_SUBDOMAINS','value'=>'www,127,2708779e7b46'],
                ['key'=>'APP_DEBUG','value'=>'true', 'ftype'=>'bool'],
                ['key'=>'QRSAAS_DISABLE_ODERING','value'=>'false', 'ftype'=>'bool','onlyin'=>"qrsaas"],
                ['key'=>'ENABLE_IMPORT_CSV','value'=>'false', 'ftype'=>'bool'],
                ['key'=>'APP_ORDER_APPROVE_DIRECTLY','value'=>'false', 'ftype'=>'bool'],
                ['key'=>'ALLOW_AUTOMATED_ASSIGN_TO_DRIVER','value'=>'true', 'ftype'=>'bool','onlyin'=>"ft"],
                ['key'=>'APP_ALLOW_SELF_DELIVER','value'=>'true', 'ftype'=>'bool','onlyin'=>"ft"],
                ['key'=>'DELIVERY_INTERVAL_IN_MINUTES','value'=>30, 'type'=>'number'],
                ['key'=>'TIME_TO_PREPARE_ORDER_IN_MINUTES','value'=>0,'type'=>'number'],
                ['key'=>'LOCATION_SEARCH_RADIUS','value'=>50, 'type'=>'number','onlyin'=>"ft"],
                ['key'=>'DRIVER_SEARCH_RADIUS','value'=>15, 'type'=>'number','onlyin'=>"ft"],
                ['key'=>'ENABLE_PICKUP','value'=>'true', 'ftype'=>'bool'],
                ['key'=>'ENABLE_COST_PER_DISTANCE','value'=>'false', 'ftype'=>'bool','onlyin'=>"ft"],
                ['key'=>'MULTI_CITY','value'=>'true', 'ftype'=>'bool','onlyin'=>"ft"],
                ['key'=>'WILDCARD_DOMAIN_READY','value'=>'false', 'ftype'=>'bool'],
                ['key'=>'SINGLE_MODE','value'=>'false', 'ftype'=>'bool','onlyin'=>"ft"],
                ['key'=>'SINGLE_MODE_ID','value'=>'1','type'=>'number','onlyin'=>"ft"],
                ['key'=>'ENABLE_GUEST_LOG','value'=>'true','ftype'=>'bool','onlyin'=>"qrsaas"],
                ['key'=>'HIDE_PROJECT_BRANDING','value'=>'true','ftype'=>'bool','onlyin'=>"qrsaas"],
                ['key'=>'MIN_PHONE_NUMBER','value'=>9, 'type'=>'number'],
                ['key'=>'URL_ROUTE','value'=>'restaurant'],
                ['key'=>'COST_PER_KILOMETER','value'=>'1','onlyin'=>"ft"],
                ['key'=>'APP_SECRET','value'=>'APP_SECRET','onlyin'=>"ft"],
                ['key'=>'APP_ENV','value'=>'local','ftype'=>'select','data'=>['local'=>"Local",'prodcution'=>"Production"]],
                ['key'=>'APP_KEY','value'=>'base64:cleqsZQ0FQGaaEpuNR228wvo02JTLgsj2Qko9Y9N4LI='],
                ['key'=>'APP_LOG_LEVEL','value'=>'debug','ftype'=>'select','data'=>['debug'=>"Debug",'error'=>"Error"]]
            ]
        ],

        [
            'name'=>"Finances",
            'slug'=>"finances",
            'icon'=>"ni ni-money-coins",
            'fields'=>[
                ['key'=>'ENABLE_STRIPE','value'=>'true' , 'ftype'=>'bool'],
                ['key'=>'STRIPE_KEY','value'=>'pk_test_XXXXXXXXXXXXXX'],
                ['key'=>'STRIPE_SECRET','value'=>'sk_test_XXXXXXXXXXXXXXX'],
                ['key'=>'ENABLE_PRICING','value'=>'true' , 'ftype'=>'bool','onlyin'=>"qrsaas"],
                ['key'=>'FREE_PRICING_ID','value'=>'1','type'=>'number','onlyin'=>"qrsaas"],
                ['key'=>'SUBSCRIPTION_PROCESSOR','value'=>'Stripe','ftype'=>'select','data'=>['Stripe'=>"Stripe",'Paddle'=>"Paddle"],'onlyin'=>"qrsaas"],
                ['key'=>'ENABLE_STRIPE_CONNECT','value'=>'true' , 'ftype'=>'bool'],
                ['key'=>'ENABLE_FINANCES_OWNER','value'=>'true' , 'ftype'=>'bool'],
                ['key'=>'ENABLE_FINANCES_ADMIN','value'=>'true' , 'ftype'=>'bool'],
                ['key'=>'HIDE_COD','value'=>'false' , 'ftype'=>'bool'],
                ['key'=>'DEFAULT_PAYMENT','value'=>'cod', 'ftype'=>'select','data'=>['cod'=>"Cash on Deliver",'stripe'=>"Stripe Card processing"] ],
                ['key'=>'PAYSTACK_PUBLIC_KEY','value'=>''],
                ['key'=>'PAYSTACK_SECRET_KEY','value'=>''],
                ['key'=>'ENABLE_PAYSTACK','value'=>'false' , 'ftype'=>'bool'],
                ['key'=>'MERCHANT_EMAIL','value'=>''],
                ['key'=>'PAYSTACK_PAYMENT_URL','value'=>'https://api.paystack.co'],
            ]
        ],
        [
            'name'=>"Localization",
            'slug'=>"localizatino",
            'icon'=>"ni ni-world-2",
            'fields'=>[
                ['key'=>'APP_LOCALE','value'=>'en','ftype'=>"select",'data'=>[
                    "af_NA"=>"Afrikaans (Namibia)",
                    "af_ZA"=>"Afrikaans (South Africa)",
                    "af"=>"Afrikaans",
                    "ak_GH"=>"Akan (Ghana)",
                    "ak"=>"Akan",
                    "sq_AL"=>"Albanian (Albania)",
                    "sq"=>"Albanian",
                    "am_ET"=>"Amharic (Ethiopia)",
                    "am"=>"Amharic",
                    "ar_DZ"=>"Arabic (Algeria)",
                    "ar_BH"=>"Arabic (Bahrain)",
                    "ar_EG"=>"Arabic (Egypt)",
                    "ar_IQ"=>"Arabic (Iraq)",
                    "ar_JO"=>"Arabic (Jordan)",
                    "ar_KW"=>"Arabic (Kuwait)",
                    "ar_LB"=>"Arabic (Lebanon)",
                    "ar_LY"=>"Arabic (Libya)",
                    "ar_MA"=>"Arabic (Morocco)",
                    "ar_OM"=>"Arabic (Oman)",
                    "ar_QA"=>"Arabic (Qatar)",
                    "ar_SA"=>"Arabic (Saudi Arabia)",
                    "ar_SD"=>"Arabic (Sudan)",
                    "ar_SY"=>"Arabic (Syria)",
                    "ar_TN"=>"Arabic (Tunisia)",
                    "ar_AE"=>"Arabic (United Arab Emirates)",
                    "ar_YE"=>"Arabic (Yemen)",
                    "ar"=>"Arabic",
                    "hy_AM"=>"Armenian (Armenia)",
                    "hy"=>"Armenian",
                    "as_IN"=>"Assamese (India)",
                    "as"=>"Assamese",
                    "asa_TZ"=>"Asu (Tanzania)",
                    "asa"=>"Asu",
                    "az_Cyrl"=>"Azerbaijani (Cyrillic)",
                    "az_Cyrl_AZ"=>"Azerbaijani (Cyrillic, Azerbaijan)",
                    "az_Latn"=>"Azerbaijani (Latin)",
                    "az_Latn_AZ"=>"Azerbaijani (Latin, Azerbaijan)",
                    "az"=>"Azerbaijani",
                    "bm_ML"=>"Bambara (Mali)",
                    "bm"=>"Bambara",
                    "eu_ES"=>"Basque (Spain)",
                    "eu"=>"Basque",
                    "be_BY"=>"Belarusian (Belarus)",
                    "be"=>"Belarusian",
                    "bem_ZM"=>"Bemba (Zambia)",
                    "bem"=>"Bemba",
                    "bez_TZ"=>"Bena (Tanzania)",
                    "bez"=>"Bena",
                    "bn_BD"=>"Bengali (Bangladesh)",
                    "bn_IN"=>"Bengali (India)",
                    "bn"=>"Bengali",
                    "bs_BA"=>"Bosnian (Bosnia and Herzegovina)",
                    "bs"=>"Bosnian",
                    "bg_BG"=>"Bulgarian (Bulgaria)",
                    "bg"=>"Bulgarian",
                    "my_MM"=>"Burmese (Myanmar [Burma])",
                    "my"=>"Burmese",
                    "yue_Hant_HK"=>"Cantonese (Traditional, Hong Kong SAR China)",
                    "ca_ES"=>"Catalan (Spain)",
                    "ca"=>"Catalan",
                    "tzm_Latn"=>"Central Morocco Tamazight (Latin)",
                    "tzm_Latn_MA"=>"Central Morocco Tamazight (Latin, Morocco)",
                    "tzm"=>"Central Morocco Tamazight",
                    "chr_US"=>"Cherokee (United States)",
                    "chr"=>"Cherokee",
                    "cgg_UG"=>"Chiga (Uganda)",
                    "cgg"=>"Chiga",
                    "zh_Hans"=>"Chinese (Simplified Han)",
                    "zh_Hans_CN"=>"Chinese (Simplified Han, China)",
                    "zh_Hans_HK"=>"Chinese (Simplified Han, Hong Kong SAR China)",
                    "zh_Hans_MO"=>"Chinese (Simplified Han, Macau SAR China)",
                    "zh_Hans_SG"=>"Chinese (Simplified Han, Singapore)",
                    "zh_Hant"=>"Chinese (Traditional Han)",
                    "zh_Hant_HK"=>"Chinese (Traditional Han, Hong Kong SAR China)",
                    "zh_Hant_MO"=>"Chinese (Traditional Han, Macau SAR China)",
                    "zh_Hant_TW"=>"Chinese (Traditional Han, Taiwan)",
                    "zh"=>"Chinese",
                    "kw_GB"=>"Cornish (United Kingdom)",
                    "kw"=>"Cornish",
                    "hr_HR"=>"Croatian (Croatia)",
                    "hr"=>"Croatian",
                    "cs_CZ"=>"Czech (Czech Republic)",
                    "cs"=>"Czech",
                    "da_DK"=>"Danish (Denmark)",
                    "da"=>"Danish",
                    "nl_BE"=>"Dutch (Belgium)",
                    "nl_NL"=>"Dutch (Netherlands)",
                    "nl"=>"Dutch",
                    "ebu_KE"=>"Embu (Kenya)",
                    "ebu"=>"Embu",
                    "en_AS"=>"English (American Samoa)",
                    "en_AU"=>"English (Australia)",
                    "en_BE"=>"English (Belgium)",
                    "en_BZ"=>"English (Belize)",
                    "en_BW"=>"English (Botswana)",
                    "en_CA"=>"English (Canada)",
                    "en_GU"=>"English (Guam)",
                    "en_HK"=>"English (Hong Kong SAR China)",
                    "en_IN"=>"English (India)",
                    "en_IE"=>"English (Ireland)",
                    "en_IL"=>"English (Israel)",
                    "en_JM"=>"English (Jamaica)",
                    "en_MT"=>"English (Malta)",
                    "en_MH"=>"English (Marshall Islands)",
                    "en_MU"=>"English (Mauritius)",
                    "en_NA"=>"English (Namibia)",
                    "en_NZ"=>"English (New Zealand)",
                    "en_MP"=>"English (Northern Mariana Islands)",
                    "en_PK"=>"English (Pakistan)",
                    "en_PH"=>"English (Philippines)",
                    "en_SG"=>"English (Singapore)",
                    "en_ZA"=>"English (South Africa)",
                    "en_TT"=>"English (Trinidad and Tobago)",
                    "en_UM"=>"English (U.S. Minor Outlying Islands)",
                    "en_VI"=>"English (U.S. Virgin Islands)",
                    "en_GB"=>"English (United Kingdom)",
                    "en_US"=>"English (United States)",
                    "en_ZW"=>"English (Zimbabwe)",
                    "en"=>"English",
                    "eo"=>"Esperanto",
                    "et_EE"=>"Estonian (Estonia)",
                    "et"=>"Estonian",
                    "ee_GH"=>"Ewe (Ghana)",
                    "ee_TG"=>"Ewe (Togo)",
                    "ee"=>"Ewe",
                    "fo_FO"=>"Faroese (Faroe Islands)",
                    "fo"=>"Faroese",
                    "fil_PH"=>"Filipino (Philippines)",
                    "fil"=>"Filipino",
                    "fi_FI"=>"Finnish (Finland)",
                    "fi"=>"Finnish",
                    "fr_BE"=>"French (Belgium)",
                    "fr_BJ"=>"French (Benin)",
                    "fr_BF"=>"French (Burkina Faso)",
                    "fr_BI"=>"French (Burundi)",
                    "fr_CM"=>"French (Cameroon)",
                    "fr_CA"=>"French (Canada)",
                    "fr_CF"=>"French (Central African Republic)",
                    "fr_TD"=>"French (Chad)",
                    "fr_KM"=>"French (Comoros)",
                    "fr_CG"=>"French (Congo - Brazzaville)",
                    "fr_CD"=>"French (Congo - Kinshasa)",
                    "fr_CI"=>"French (Côte d’Ivoire)",
                    "fr_DJ"=>"French (Djibouti)",
                    "fr_GQ"=>"French (Equatorial Guinea)",
                    "fr_FR"=>"French (France)",
                    "fr_GA"=>"French (Gabon)",
                    "fr_GP"=>"French (Guadeloupe)",
                    "fr_GN"=>"French (Guinea)",
                    "fr_LU"=>"French (Luxembourg)",
                    "fr_MG"=>"French (Madagascar)",
                    "fr_ML"=>"French (Mali)",
                    "fr_MQ"=>"French (Martinique)",
                    "fr_MC"=>"French (Monaco)",
                    "fr_NE"=>"French (Niger)",
                    "fr_RW"=>"French (Rwanda)",
                    "fr_RE"=>"French (Réunion)",
                    "fr_BL"=>"French (Saint Barthélemy)",
                    "fr_MF"=>"French (Saint Martin)",
                    "fr_SN"=>"French (Senegal)",
                    "fr_CH"=>"French (Switzerland)",
                    "fr_TG"=>"French (Togo)",
                    "fr"=>"French",
                    "ff_SN"=>"Fulah (Senegal)",
                    "ff"=>"Fulah",
                    "gl_ES"=>"Galician (Spain)",
                    "gl"=>"Galician",
                    "lg_UG"=>"Ganda (Uganda)",
                    "lg"=>"Ganda",
                    "ka_GE"=>"Georgian (Georgia)",
                    "ka"=>"Georgian",
                    "de_AT"=>"German (Austria)",
                    "de_BE"=>"German (Belgium)",
                    "de_DE"=>"German (Germany)",
                    "de_LI"=>"German (Liechtenstein)",
                    "de_LU"=>"German (Luxembourg)",
                    "de_CH"=>"German (Switzerland)",
                    "de"=>"German",
                    "el_CY"=>"Greek (Cyprus)",
                    "el_GR"=>"Greek (Greece)",
                    "el"=>"Greek",
                    "gu_IN"=>"Gujarati (India)",
                    "gu"=>"Gujarati",
                    "guz_KE"=>"Gusii (Kenya)",
                    "guz"=>"Gusii",
                    "ha_Latn"=>"Hausa (Latin)",
                    "ha_Latn_GH"=>"Hausa (Latin, Ghana)",
                    "ha_Latn_NE"=>"Hausa (Latin, Niger)",
                    "ha_Latn_NG"=>"Hausa (Latin, Nigeria)",
                    "ha"=>"Hausa",
                    "haw_US"=>"Hawaiian (United States)",
                    "haw"=>"Hawaiian",
                    "he_IL"=>"Hebrew (Israel)",
                    "he"=>"Hebrew",
                    "hi_IN"=>"Hindi (India)",
                    "hi"=>"Hindi",
                    "hu_HU"=>"Hungarian (Hungary)",
                    "hu"=>"Hungarian",
                    "is_IS"=>"Icelandic (Iceland)",
                    "is"=>"Icelandic",
                    "ig_NG"=>"Igbo (Nigeria)",
                    "ig"=>"Igbo",
                    "id_ID"=>"Indonesian (Indonesia)",
                    "id"=>"Indonesian",
                    "ga_IE"=>"Irish (Ireland)",
                    "ga"=>"Irish",
                    "it_IT"=>"Italian (Italy)",
                    "it_CH"=>"Italian (Switzerland)",
                    "it"=>"Italian",
                    "ja_JP"=>"Japanese (Japan)",
                    "ja"=>"Japanese",
                    "kea_CV"=>"Kabuverdianu (Cape Verde)",
                    "kea"=>"Kabuverdianu",
                    "kab_DZ"=>"Kabyle (Algeria)",
                    "kab"=>"Kabyle",
                    "kl_GL"=>"Kalaallisut (Greenland)",
                    "kl"=>"Kalaallisut",
                    "kln_KE"=>"Kalenjin (Kenya)",
                    "kln"=>"Kalenjin",
                    "kam_KE"=>"Kamba (Kenya)",
                    "kam"=>"Kamba",
                    "kn_IN"=>"Kannada (India)",
                    "kn"=>"Kannada",
                    "kk_Cyrl"=>"Kazakh (Cyrillic)",
                    "kk_Cyrl_KZ"=>"Kazakh (Cyrillic, Kazakhstan)",
                    "kk"=>"Kazakh",
                    "km_KH"=>"Khmer (Cambodia)",
                    "km"=>"Khmer",
                    "ki_KE"=>"Kikuyu (Kenya)",
                    "ki"=>"Kikuyu",
                    "rw_RW"=>"Kinyarwanda (Rwanda)",
                    "rw"=>"Kinyarwanda",
                    "kok_IN"=>"Konkani (India)",
                    "kok"=>"Konkani",
                    "ko_KR"=>"Korean (South Korea)",
                    "ko"=>"Korean",
                    "khq_ML"=>"Koyra Chiini (Mali)",
                    "khq"=>"Koyra Chiini",
                    "ses_ML"=>"Koyraboro Senni (Mali)",
                    "ses"=>"Koyraboro Senni",
                    "lag_TZ"=>"Langi (Tanzania)",
                    "lag"=>"Langi",
                    "lv_LV"=>"Latvian (Latvia)",
                    "lv"=>"Latvian",
                    "lt_LT"=>"Lithuanian (Lithuania)",
                    "lt"=>"Lithuanian",
                    "luo_KE"=>"Luo (Kenya)",
                    "luo"=>"Luo",
                    "luy_KE"=>"Luyia (Kenya)",
                    "luy"=>"Luyia",
                    "mk_MK"=>"Macedonian (Macedonia)",
                    "mk"=>"Macedonian",
                    "jmc_TZ"=>"Machame (Tanzania)",
                    "jmc"=>"Machame",
                    "kde_TZ"=>"Makonde (Tanzania)",
                    "kde"=>"Makonde",
                    "mg_MG"=>"Malagasy (Madagascar)",
                    "mg"=>"Malagasy",
                    "ms_BN"=>"Malay (Brunei)",
                    "ms_MY"=>"Malay (Malaysia)",
                    "ms"=>"Malay",
                    "ml_IN"=>"Malayalam (India)",
                    "ml"=>"Malayalam",
                    "mt_MT"=>"Maltese (Malta)",
                    "mt"=>"Maltese",
                    "gv_GB"=>"Manx (United Kingdom)",
                    "gv"=>"Manx",
                    "mr_IN"=>"Marathi (India)",
                    "mr"=>"Marathi",
                    "mas_KE"=>"Masai (Kenya)",
                    "mas_TZ"=>"Masai (Tanzania)",
                    "mas"=>"Masai",
                    "mer_KE"=>"Meru (Kenya)",
                    "mer"=>"Meru",
                    "mfe_MU"=>"Morisyen (Mauritius)",
                    "mfe"=>"Morisyen",
                    "naq_NA"=>"Nama (Namibia)",
                    "naq"=>"Nama",
                    "ne_IN"=>"Nepali (India)",
                    "ne_NP"=>"Nepali (Nepal)",
                    "ne"=>"Nepali",
                    "nd_ZW"=>"North Ndebele (Zimbabwe)",
                    "nd"=>"North Ndebele",
                    "nb_NO"=>"Norwegian Bokmål (Norway)",
                    "nb"=>"Norwegian Bokmål",
                    "nn_NO"=>"Norwegian Nynorsk (Norway)",
                    "nn"=>"Norwegian Nynorsk",
                    "nyn_UG"=>"Nyankole (Uganda)",
                    "nyn"=>"Nyankole",
                    "or_IN"=>"Oriya (India)",
                    "or"=>"Oriya",
                    "om_ET"=>"Oromo (Ethiopia)",
                    "om_KE"=>"Oromo (Kenya)",
                    "om"=>"Oromo",
                    "ps_AF"=>"Pashto (Afghanistan)",
                    "ps"=>"Pashto",
                    "fa_AF"=>"Persian (Afghanistan)",
                    "fa_IR"=>"Persian (Iran)",
                    "fa"=>"Persian",
                    "pl_PL"=>"Polish (Poland)",
                    "pl"=>"Polish",
                    "pt_BR"=>"Portuguese (Brazil)",
                    "pt_GW"=>"Portuguese (Guinea-Bissau)",
                    "pt_MZ"=>"Portuguese (Mozambique)",
                    "pt_PT"=>"Portuguese (Portugal)",
                    "pt"=>"Portuguese",
                    "pa_Arab"=>"Punjabi (Arabic)",
                    "pa_Arab_PK"=>"Punjabi (Arabic, Pakistan)",
                    "pa_Guru"=>"Punjabi (Gurmukhi)",
                    "pa_Guru_IN"=>"Punjabi (Gurmukhi, India)",
                    "pa"=>"Punjabi",
                    "ro_MD"=>"Romanian (Moldova)",
                    "ro_RO"=>"Romanian (Romania)",
                    "ro"=>"Romanian",
                    "rm_CH"=>"Romansh (Switzerland)",
                    "rm"=>"Romansh",
                    "rof_TZ"=>"Rombo (Tanzania)",
                    "rof"=>"Rombo",
                    "ru_MD"=>"Russian (Moldova)",
                    "ru_RU"=>"Russian (Russia)",
                    "ru_UA"=>"Russian (Ukraine)",
                    "ru"=>"Russian",
                    "rwk_TZ"=>"Rwa (Tanzania)",
                    "rwk"=>"Rwa",
                    "saq_KE"=>"Samburu (Kenya)",
                    "saq"=>"Samburu",
                    "sg_CF"=>"Sango (Central African Republic)",
                    "sg"=>"Sango",
                    "seh_MZ"=>"Sena (Mozambique)",
                    "seh"=>"Sena",
                    "sr_Cyrl"=>"Serbian (Cyrillic)",
                    "sr_Cyrl_BA"=>"Serbian (Cyrillic, Bosnia and Herzegovina)",
                    "sr_Cyrl_ME"=>"Serbian (Cyrillic, Montenegro)",
                    "sr_Cyrl_RS"=>"Serbian (Cyrillic, Serbia)",
                    "sr_Latn"=>"Serbian (Latin)",
                    "sr_Latn_BA"=>"Serbian (Latin, Bosnia and Herzegovina)",
                    "sr_Latn_ME"=>"Serbian (Latin, Montenegro)",
                    "sr_Latn_RS"=>"Serbian (Latin, Serbia)",
                    "sr"=>"Serbian",
                    "sn_ZW"=>"Shona (Zimbabwe)",
                    "sn"=>"Shona",
                    "ii_CN"=>"Sichuan Yi (China)",
                    "ii"=>"Sichuan Yi",
                    "si_LK"=>"Sinhala (Sri Lanka)",
                    "si"=>"Sinhala",
                    "sk_SK"=>"Slovak (Slovakia)",
                    "sk"=>"Slovak",
                    "sl_SI"=>"Slovenian (Slovenia)",
                    "sl"=>"Slovenian",
                    "xog_UG"=>"Soga (Uganda)",
                    "xog"=>"Soga",
                    "so_DJ"=>"Somali (Djibouti)",
                    "so_ET"=>"Somali (Ethiopia)",
                    "so_KE"=>"Somali (Kenya)",
                    "so_SO"=>"Somali (Somalia)",
                    "so"=>"Somali",
                    "es_AR"=>"Spanish (Argentina)",
                    "es_BO"=>"Spanish (Bolivia)",
                    "es_CL"=>"Spanish (Chile)",
                    "es_CO"=>"Spanish (Colombia)",
                    "es_CR"=>"Spanish (Costa Rica)",
                    "es_DO"=>"Spanish (Dominican Republic)",
                    "es_EC"=>"Spanish (Ecuador)",
                    "es_SV"=>"Spanish (El Salvador)",
                    "es_GQ"=>"Spanish (Equatorial Guinea)",
                    "es_GT"=>"Spanish (Guatemala)",
                    "es_HN"=>"Spanish (Honduras)",
                    "es_419"=>"Spanish (Latin America)",
                    "es_MX"=>"Spanish (Mexico)",
                    "es_NI"=>"Spanish (Nicaragua)",
                    "es_PA"=>"Spanish (Panama)",
                    "es_PY"=>"Spanish (Paraguay)",
                    "es_PE"=>"Spanish (Peru)",
                    "es_PR"=>"Spanish (Puerto Rico)",
                    "es_ES"=>"Spanish (Spain)",
                    "es_US"=>"Spanish (United States)",
                    "es_UY"=>"Spanish (Uruguay)",
                    "es_VE"=>"Spanish (Venezuela)",
                    "es"=>"Spanish",
                    "sw_KE"=>"Swahili (Kenya)",
                    "sw_TZ"=>"Swahili (Tanzania)",
                    "sw"=>"Swahili",
                    "sv_FI"=>"Swedish (Finland)",
                    "sv_SE"=>"Swedish (Sweden)",
                    "sv"=>"Swedish",
                    "gsw_CH"=>"Swiss German (Switzerland)",
                    "gsw"=>"Swiss German",
                    "shi_Latn"=>"Tachelhit (Latin)",
                    "shi_Latn_MA"=>"Tachelhit (Latin, Morocco)",
                    "shi_Tfng"=>"Tachelhit (Tifinagh)",
                    "shi_Tfng_MA"=>"Tachelhit (Tifinagh, Morocco)",
                    "shi"=>"Tachelhit",
                    "dav_KE"=>"Taita (Kenya)",
                    "dav"=>"Taita",
                    "ta_IN"=>"Tamil (India)",
                    "ta_LK"=>"Tamil (Sri Lanka)",
                    "ta"=>"Tamil",
                    "te_IN"=>"Telugu (India)",
                    "te"=>"Telugu",
                    "teo_KE"=>"Teso (Kenya)",
                    "teo_UG"=>"Teso (Uganda)",
                    "teo"=>"Teso",
                    "th_TH"=>"Thai (Thailand)",
                    "th"=>"Thai",
                    "bo_CN"=>"Tibetan (China)",
                    "bo_IN"=>"Tibetan (India)",
                    "bo"=>"Tibetan",
                    "ti_ER"=>"Tigrinya (Eritrea)",
                    "ti_ET"=>"Tigrinya (Ethiopia)",
                    "ti"=>"Tigrinya",
                    "to_TO"=>"Tonga (Tonga)",
                    "to"=>"Tonga",
                    "tr_TR"=>"Turkish (Turkey)",
                    "tr"=>"Turkish",
                    "uk_UA"=>"Ukrainian (Ukraine)",
                    "uk"=>"Ukrainian",
                    "ur_IN"=>"Urdu (India)",
                    "ur_PK"=>"Urdu (Pakistan)",
                    "ur"=>"Urdu",
                    "uz_Arab"=>"Uzbek (Arabic)",
                    "uz_Arab_AF"=>"Uzbek (Arabic, Afghanistan)",
                    "uz_Cyrl"=>"Uzbek (Cyrillic)",
                    "uz_Cyrl_UZ"=>"Uzbek (Cyrillic, Uzbekistan)",
                    "uz_Latn"=>"Uzbek (Latin)",
                    "uz_Latn_UZ"=>"Uzbek (Latin, Uzbekistan)",
                    "uz"=>"Uzbek",
                    "vi_VN"=>"Vietnamese (Vietnam)",
                    "vi"=>"Vietnamese",
                    "vun_TZ"=>"Vunjo (Tanzania)",
                    "vun"=>"Vunjo",
                    "cy_GB"=>"Welsh (United Kingdom)",
                    "cy"=>"Welsh",
                    "yo_NG"=>"Yoruba (Nigeria)",
                    "yo"=>"Yoruba",
                    "zu_ZA"=>"Zulu (South Africa)",
                    "zu"=>"Zulu"
                ]],
                ['key'=>'TIME_ZONE','value'=>'Europe/Berlin', 'ftype'=>"select", 'data'=>[
                    "Pacific/Midway"=>"(UTC-11:00) Midway Island",
                    "Pacific/Samoa"=>"(UTC-11:00) Samoa",
                    "Pacific/Honolulu"=>"(UTC-10:00) Hawaii",
                    "US/Alaska"=>"(UTC-09:00) Alaska",
                    "America/Los_Angeles"=>"(UTC-08:00) Pacific Time (US &amp; Canada)",
                    "America/Tijuana"=>"(UTC-08:00) Tijuana",
                    "US/Arizona"=>"(UTC-07:00) Arizona",
                    "America/Chihuahua"=>"(UTC-07:00) Chihuahua",
                    "America/Chihuahua"=>"(UTC-07:00) La Paz",
                    "America/Mazatlan"=>"(UTC-07:00) Mazatlan",
                    "US/Mountain"=>"(UTC-07:00) Mountain Time (US &amp; Canada)",
                    "America/Managua"=>"(UTC-06:00) Central America",
                    "US/Central"=>"(UTC-06:00) Central Time (US &amp; Canada)",
                    "America/Mexico_City"=>"(UTC-06:00) Guadalajara",
                    "America/Mexico_City"=>"(UTC-06:00) Mexico City",
                    "America/Monterrey"=>"(UTC-06:00) Monterrey",
                    "Canada/Saskatchewan"=>"(UTC-06:00) Saskatchewan",
                    "America/Bogota"=>"(UTC-05:00) Bogota",
                    "US/Eastern"=>"(UTC-05:00) Eastern Time (US &amp; Canada)",
                    "US/East-Indiana"=>"(UTC-05:00) Indiana (East)",
                    "America/Lima"=>"(UTC-05:00) Lima",
                    "America/Bogota"=>"(UTC-05:00) Quito",
                    "Canada/Atlantic"=>"(UTC-04:00) Atlantic Time (Canada)",
                    "America/Caracas"=>"(UTC-04:30) Caracas",
                    "America/La_Paz"=>"(UTC-04:00) La Paz",
                    "America/Santiago"=>"(UTC-04:00) Santiago",
                    "Canada/Newfoundland"=>"(UTC-03:30) Newfoundland",
                    "America/Sao_Paulo"=>"(UTC-03:00) Brasilia",
                    "America/Argentina/Buenos_Aires"=>"(UTC-03:00) Buenos Aires",
                    "America/Argentina/Buenos_Aires"=>"(UTC-03:00) Georgetown",
                    "America/Godthab"=>"(UTC-03:00) Greenland",
                    "America/Noronha"=>"(UTC-02:00) Mid-Atlantic",
                    "Atlantic/Azores"=>"(UTC-01:00) Azores",
                    "Atlantic/Cape_Verde"=>"(UTC-01:00) Cape Verde Is.",
                    "Africa/Casablanca"=>"(UTC+00:00) Casablanca",
                    "Europe/London"=>"(UTC+00:00) Edinburgh",
                    "Etc/Greenwich"=>"(UTC+00:00) Greenwich Mean Time : Dublin",
                    "Europe/Lisbon"=>"(UTC+00:00) Lisbon",
                    "Europe/London"=>"(UTC+00:00) London",
                    "Africa/Monrovia"=>"(UTC+00:00) Monrovia",
                    "UTC"=>"(UTC+00:00) UTC",
                    "Europe/Amsterdam"=>"(UTC+01:00) Amsterdam",
                    "Europe/Belgrade"=>"(UTC+01:00) Belgrade",
                    "Europe/Berlin"=>"(UTC+01:00) Berlin",
                    "Europe/Berlin"=>"(UTC+01:00) Bern",
                    "Europe/Bratislava"=>"(UTC+01:00) Bratislava",
                    "Europe/Brussels"=>"(UTC+01:00) Brussels",
                    "Europe/Budapest"=>"(UTC+01:00) Budapest",
                    "Europe/Copenhagen"=>"(UTC+01:00) Copenhagen",
                    "Europe/Ljubljana"=>"(UTC+01:00) Ljubljana",
                    "Europe/Madrid"=>"(UTC+01:00) Madrid",
                    "Europe/Paris"=>"(UTC+01:00) Paris",
                    "Europe/Prague"=>"(UTC+01:00) Prague",
                    "Europe/Rome"=>"(UTC+01:00) Rome",
                    "Europe/Sarajevo"=>"(UTC+01:00) Sarajevo",
                    "Europe/Skopje"=>"(UTC+01:00) Skopje",
                    "Europe/Stockholm"=>"(UTC+01:00) Stockholm",
                    "Europe/Vienna"=>"(UTC+01:00) Vienna",
                    "Europe/Warsaw"=>"(UTC+01:00) Warsaw",
                    "Africa/Lagos"=>"(UTC+01:00) West Central Africa",
                    "Europe/Zagreb"=>"(UTC+01:00) Zagreb",
                    "Europe/Athens"=>"(UTC+02:00) Athens",
                    "Europe/Bucharest"=>"(UTC+02:00) Bucharest",
                    "Africa/Cairo"=>"(UTC+02:00) Cairo",
                    "Africa/Harare"=>"(UTC+02:00) Harare",
                    "Europe/Helsinki"=>"(UTC+02:00) Helsinki",
                    "Europe/Istanbul"=>"(UTC+02:00) Istanbul",
                    "Asia/Jerusalem"=>"(UTC+02:00) Jerusalem",
                    "Europe/Helsinki"=>"(UTC+02:00) Kyiv",
                    "Africa/Johannesburg"=>"(UTC+02:00) Pretoria",
                    "Europe/Riga"=>"(UTC+02:00) Riga",
                    "Europe/Sofia"=>"(UTC+02:00) Sofia",
                    "Europe/Tallinn"=>"(UTC+02:00) Tallinn",
                    "Europe/Vilnius"=>"(UTC+02:00) Vilnius",
                    "Asia/Baghdad"=>"(UTC+03:00) Baghdad",
                    "Asia/Kuwait"=>"(UTC+03:00) Kuwait",
                    "Europe/Minsk"=>"(UTC+03:00) Minsk",
                    "Africa/Nairobi"=>"(UTC+03:00) Nairobi",
                    "Asia/Riyadh"=>"(UTC+03:00) Riyadh",
                    "Europe/Volgograd"=>"(UTC+03:00) Volgograd",
                    "Asia/Tehran"=>"(UTC+03:30) Tehran",
                    "Asia/Muscat"=>"(UTC+04:00) Abu Dhabi",
                    "Asia/Baku"=>"(UTC+04:00) Baku",
                    "Europe/Moscow"=>"(UTC+04:00) Moscow",
                    "Asia/Muscat"=>"(UTC+04:00) Muscat",
                    "Europe/Moscow"=>"(UTC+04:00) St. Petersburg",
                    "Asia/Tbilisi"=>"(UTC+04:00) Tbilisi",
                    "Asia/Yerevan"=>"(UTC+04:00) Yerevan",
                    "Asia/Kabul"=>"(UTC+04:30) Kabul",
                    "Asia/Karachi"=>"(UTC+05:00) Islamabad",
                    "Asia/Karachi"=>"(UTC+05:00) Karachi",
                    "Asia/Tashkent"=>"(UTC+05:00) Tashkent",
                    "Asia/Calcutta"=>"(UTC+05:30) Chennai",
                    "Asia/Kolkata"=>"(UTC+05:30) Kolkata",
                    "Asia/Calcutta"=>"(UTC+05:30) Mumbai",
                    "Asia/Calcutta"=>"(UTC+05:30) New Delhi",
                    "Asia/Calcutta"=>"(UTC+05:30) Sri Jayawardenepura",
                    "Asia/Katmandu"=>"(UTC+05:45) Kathmandu",
                    "Asia/Almaty"=>"(UTC+06:00) Almaty",
                    "Asia/Dhaka"=>"(UTC+06:00) Astana",
                    "Asia/Dhaka"=>"(UTC+06:00) Dhaka",
                    "Asia/Yekaterinburg"=>"(UTC+06:00) Ekaterinburg",
                    "Asia/Rangoon"=>"(UTC+06:30) Rangoon",
                    "Asia/Bangkok"=>"(UTC+07:00) Bangkok",
                    "Asia/Bangkok"=>"(UTC+07:00) Hanoi",
                    "Asia/Jakarta"=>"(UTC+07:00) Jakarta",
                    "Asia/Novosibirsk"=>"(UTC+07:00) Novosibirsk",
                    "Asia/Hong_Kong"=>"(UTC+08:00) Beijing",
                    "Asia/Chongqing"=>"(UTC+08:00) Chongqing",
                    "Asia/Hong_Kong"=>"(UTC+08:00) Hong Kong",
                    "Asia/Krasnoyarsk"=>"(UTC+08:00) Krasnoyarsk",
                    "Asia/Kuala_Lumpur"=>"(UTC+08:00) Kuala Lumpur",
                    "Australia/Perth"=>"(UTC+08:00) Perth",
                    "Asia/Singapore"=>"(UTC+08:00) Singapore",
                    "Asia/Taipei"=>"(UTC+08:00) Taipei",
                    "Asia/Ulan_Bator"=>"(UTC+08:00) Ulaan Bataar",
                    "Asia/Urumqi"=>"(UTC+08:00) Urumqi",
                    "Asia/Irkutsk"=>"(UTC+09:00) Irkutsk",
                    "Asia/Tokyo"=>"(UTC+09:00) Osaka",
                    "Asia/Tokyo"=>"(UTC+09:00) Sapporo",
                    "Asia/Seoul"=>"(UTC+09:00) Seoul",
                    "Asia/Tokyo"=>"(UTC+09:00) Tokyo",
                    "Australia/Adelaide"=>"(UTC+09:30) Adelaide",
                    "Australia/Darwin"=>"(UTC+09:30) Darwin",
                    "Australia/Brisbane"=>"(UTC+10:00) Brisbane",
                    "Australia/Canberra"=>"(UTC+10:00) Canberra",
                    "Pacific/Guam"=>"(UTC+10:00) Guam",
                    "Australia/Hobart"=>"(UTC+10:00) Hobart",
                    "Australia/Melbourne"=>"(UTC+10:00) Melbourne",
                    "Pacific/Port_Moresby"=>"(UTC+10:00) Port Moresby",
                    "Australia/Sydney"=>"(UTC+10:00) Sydney",
                    "Asia/Yakutsk"=>"(UTC+10:00) Yakutsk",
                    "Asia/Vladivostok"=>"(UTC+11:00) Vladivostok",
                    "Pacific/Auckland"=>"(UTC+12:00) Auckland",
                    "Pacific/Fiji"=>"(UTC+12:00) Fiji",
                    "Pacific/Kwajalein"=>"(UTC+12:00) International Date Line West",
                    "Asia/Kamchatka"=>"(UTC+12:00) Kamchatka",
                    "Asia/Magadan"=>"(UTC+12:00) Magadan",
                    "Pacific/Fiji"=>"(UTC+12:00) Marshall Is.",
                    "Asia/Magadan"=>"(UTC+12:00) New Caledonia",
                    "Asia/Magadan"=>"(UTC+12:00) Solomon Is.",
                    "Pacific/Auckland"=>"(UTC+12:00) Wellington",
                    "Pacific/Tongatapu"=>"(UTC+13:00) Nuku'alofa",
                ]],
                ['key'=>'CASHIER_CURRENCY','value'=>'eur','ftype'=>"select",'data'=>[
                    'ALL' => 'Albania Lek',
                    'AFN' => 'Afghanistan Afghani',
                    'ARS' => 'Argentina Peso',
                    'AWG' => 'Aruba Guilder',
                    'AUD' => 'Australia Dollar',
                    'AZN' => 'Azerbaijan New Manat',
                    'BSD' => 'Bahamas Dollar',
                    'BBD' => 'Barbados Dollar',
                    'BDT' => 'Bangladeshi taka',
                    'BYR' => 'Belarus Ruble',
                    'BZD' => 'Belize Dollar',
                    'BMD' => 'Bermuda Dollar',
                    'BOB' => 'Bolivia Boliviano',
                    'BAM' => 'Bosnia and Herzegovina Convertible Marka',
                    'BWP' => 'Botswana Pula',
                    'BGN' => 'Bulgaria Lev',
                    'BRL' => 'Brazil Real',
                    'BND' => 'Brunei Darussalam Dollar',
                    'KHR' => 'Cambodia Riel',
                    'CAD' => 'Canada Dollar',
                    'KYD' => 'Cayman Islands Dollar',
                    'CLP' => 'Chile Peso',
                    'CNY' => 'China Yuan Renminbi',
                    'COP' => 'Colombia Peso',
                    'CRC' => 'Costa Rica Colon',
                    'HRK' => 'Croatia Kuna',
                    'CUP' => 'Cuba Peso',
                    'CZK' => 'Czech Republic Koruna',
                    'DKK' => 'Denmark Krone',
                    'DOP' => 'Dominican Republic Peso',
                    'XCD' => 'East Caribbean Dollar',
                    'EGP' => 'Egypt Pound',
                    'SVC' => 'El Salvador Colon',
                    'EEK' => 'Estonia Kroon',
                    'EUR' => 'Euro Member Countries',
                    'FKP' => 'Falkland Islands (Malvinas) Pound',
                    'FJD' => 'Fiji Dollar',
                    'GHC' => 'Ghana Cedis',
                    'GIP' => 'Gibraltar Pound',
                    'GTQ' => 'Guatemala Quetzal',
                    'GGP' => 'Guernsey Pound',
                    'GYD' => 'Guyana Dollar',
                    'HNL' => 'Honduras Lempira',
                    'HKD' => 'Hong Kong Dollar',
                    'HUF' => 'Hungary Forint',
                    'ISK' => 'Iceland Krona',
                    'INR' => 'India Rupee',
                    'IDR' => 'Indonesia Rupiah',
                    'IRR' => 'Iran Rial',
                    'IMP' => 'Isle of Man Pound',
                    'ILS' => 'Israel Shekel',
                    'JMD' => 'Jamaica Dollar',
                    'JPY' => 'Japan Yen',
                    'JEP' => 'Jersey Pound',
                    'KZT' => 'Kazakhstan Tenge',
                    'KPW' => 'Korea (North) Won',
                    'KRW' => 'Korea (South) Won',
                    'KGS' => 'Kyrgyzstan Som',
                    'LAK' => 'Laos Kip',
                    'LVL' => 'Latvia Lat',
                    'LBP' => 'Lebanon Pound',
                    'LRD' => 'Liberia Dollar',
                    'LTL' => 'Lithuania Litas',
                    'MKD' => 'Macedonia Denar',
                    'MYR' => 'Malaysia Ringgit',
                    'MUR' => 'Mauritius Rupee',
                    'MXN' => 'Mexico Peso',
                    'MNT' => 'Mongolia Tughrik',
                    'MZN' => 'Mozambique Metical',
                    'NAD' => 'Namibia Dollar',
                    'NPR' => 'Nepal Rupee',
                    'ANG' => 'Netherlands Antilles Guilder',
                    'NZD' => 'New Zealand Dollar',
                    'NIO' => 'Nicaragua Cordoba',
                    'NGN' => 'Nigeria Naira',
                    'NOK' => 'Norway Krone',
                    'OMR' => 'Oman Rial',
                    'PKR' => 'Pakistan Rupee',
                    'PAB' => 'Panama Balboa',
                    'PYG' => 'Paraguay Guarani',
                    'PEN' => 'Peru Nuevo Sol',
                    'PHP' => 'Philippines Peso',
                    'PLN' => 'Poland Zloty',
                    'QAR' => 'Qatar Riyal',
                    'RON' => 'Romania New Leu',
                    'RUB' => 'Russia Ruble',
                    'SHP' => 'Saint Helena Pound',
                    'SAR' => 'Saudi Arabia Riyal',
                    'RSD' => 'Serbia Dinar',
                    'SCR' => 'Seychelles Rupee',
                    'SGD' => 'Singapore Dollar',
                    'SBD' => 'Solomon Islands Dollar',
                    'SOS' => 'Somalia Shilling',
                    'ZAR' => 'South Africa Rand',
                    'LKR' => 'Sri Lanka Rupee',
                    'SEK' => 'Sweden Krona',
                    'CHF' => 'Switzerland Franc',
                    'SRD' => 'Suriname Dollar',
                    'SYP' => 'Syria Pound',
                    'TWD' => 'Taiwan New Dollar',
                    'THB' => 'Thailand Baht',
                    'TTD' => 'Trinidad and Tobago Dollar',
                    'TRY' => 'Turkey Lira',
                    'TRL' => 'Turkey Lira',
                    'TVD' => 'Tuvalu Dollar',
                    'UAH' => 'Ukraine Hryvna',
                    'GBP' => 'United Kingdom Pound',
                    'USD' => 'United States Dollar',
                    'UYU' => 'Uruguay Peso',
                    'UZS' => 'Uzbekistan Som',
                    'VEF' => 'Venezuela Bolivar',
                    'VND' => 'Viet Nam Dong',
                    'YER' => 'Yemen Rial',
                    'ZWD' => 'Zimbabwe Dollar'
                ]],
                ['key'=>'DO_CONVERTION','value'=>'true','ftype'=>"bool"],
                ['key'=>'TIME_FORMAT','value'=>'AM/PM','ftype'=>"select",'data'=>['AM/PM'=>"AM/PM",'24hours '=>"24 Hours"]],
                ['key'=>'DATETIME_DISPLAY_FORMAT','value'=>'"d M Y h:i A"'],
                ['key'=>'FRONT_LANGUAGES','value'=>'EN,English,FR,French'],

            ]
        ],
        [
            'name'=>"Plugins",
            'slug'=>"plugins",
            'icon'=>"ni ni-ui-04",
            'fields'=>[
                ['key'=>'RECAPTCHA_SITE_KEY','value'=>''],
                ['key'=>'RECAPTCHA_SECRET_KEY','value'=>''],
                ['key'=>'GOOGLE_MAPS_API_KEY','value'=>''],
                ['key'=>'ENABLE_LOCATION_SEARCH','value'=>'false' , 'ftype'=>'bool','onlyin'=>"ft"],
                ['key'=>'GOOGLE_ANALYTICS','value'=>''],
                ['key'=>'GOOGLE_CLIENT_ID','value'=>'','onlyin'=>"ft"],
                ['key'=>'GOOGLE_CLIENT_SECRET','value'=>'','onlyin'=>"ft"],
                ['key'=>'GOOGLE_REDIRECT','value'=>'','onlyin'=>"ft"],
                ['key'=>'FACEBOOK_CLIENT_ID','value'=>'','onlyin'=>"ft"],
                ['key'=>'FACEBOOK_CLIENT_SECRET','value'=>'','onlyin'=>"ft"],
                ['key'=>'FACEBOOK_REDIRECT','value'=>'','onlyin'=>"ft"],
                ['key'=>'ONESIGNAL_APP_ID','value'=>'','onlyin'=>"ft"],
                ['key'=>'ONESIGNAL_REST_API_KEY','value'=>'','onlyin'=>"ft"],
                ['key'=>'TWILIO_ACCOUNT_SID','value'=>'SID','onlyin'=>"ft"],
                ['key'=>'TWILIO_AUTH_TOKEN','value'=>'TOKEN','onlyin'=>"ft"],
                ['key'=>'TWILIO_FROM','value'=>'NUMBER','onlyin'=>"ft"],
                ['key'=>'SEND_SMS_NOTIFICATIONS','value'=>'false', 'ftype'=>'bool','onlyin'=>"ft"]
            ]
        ],
        [
            'name'=>"SMTP",
            'slug'=>"smtp",
            'icon'=>"ni ni-email-83",
            'fields'=>[
                [ 'key'=>'MAIL_DRIVER','value'=>'smtp','ftype'=>"select",'data'=>['smtp'=>"SMTP",'sendmail'=>"PHP Sendmail"]],
                [ 'key'=>'MAIL_HOST','value'=>'smtp.mailtrap.io','hint'=>"Your SMTP send server"],
                [ 'key'=>'MAIL_PORT','value'=>'2525'],
                [ 'key'=>'MAIL_USERNAME','value'=>'802fc656dd8029'],
                [ 'key'=>'MAIL_PASSWORD','value'=>'bbcf39d313eac6'],
                [ 'key'=>'MAIL_FROM_ADDRESS','value'=>'bd5d577b7c-be3ae1@inbox.mailtrap.io'],
                [ 'key'=>'MAIL_FROM_NAME','value'=>'Your Site']
            ]
        ],
        [
            'name'=>"Database",
            'icon'=>"ni ni-single-copy-04",
            'slug'=>"database",
            'fields'=>[
                [ 'key'=>'DB_CONNECTION','value'=>'mysql','ftype'=>"select",'data'=>['mysql'=>"MySql"]],
                [ 'key'=>'DB_HOST','value'=>'127.0.0.1','hint'=>"Your SMTP send server"],
                [ 'key'=>'DB_PORT','value'=>'3306'],
                [ 'key'=>'DB_DATABASE','value'=>'laravel'],
                [ 'key'=>'DB_USERNAME','value'=>'laravel'],
                [ 'key'=>'DB_PASSWORD','value'=>'laravel'],

                ['key'=>'BROADCAST_DRIVER','value'=>'log', 'type'=>'hidden'],
                ['key'=>'CACHE_DRIVER','value'=>'file', 'type'=>'hidden'],
                ['key'=>'SESSION_DRIVER','value'=>'file', 'type'=>'hidden'],
                ['key'=>'QUEUE_DRIVER','value'=>'sync', 'type'=>'hidden'],
                ['key'=>'REDIS_HOST','value'=>'127.0.0.1', 'type'=>'hidden'],
                ['key'=>'REDIS_PASSWORD','value'=>'null', 'type'=>'hidden'],
                ['key'=>'REDIS_PORT','value'=>'6379', 'type'=>'hidden'],
                ['key'=>'PUSHER_APP_ID','value'=>'', 'type'=>'hidden'],
                ['key'=>'PUSHER_APP_KEY','value'=>'', 'type'=>'hidden'],
                ['key'=>'PUSHER_APP_SECRET','value'=>'', 'type'=>'hidden'],
            ]
        ]
    ]
];